# coding=UTF-8
import csv, codecs

trans = {
    '土耳其共和國': 'TRU',
    '大陸地區': 'CHN',
    '大韓民國(南韓)': 'KOR',
    '丹麥王國': 'DNK',
    '厄瓜多共和國': 'ECU',
    '巴西聯邦共和國': 'BRA',
    '巴拿馬共和國': 'PAN',
    '日本': 'JPN',
    '比利時王國': 'BEL',
    '牙買加': 'JAM',
    '以色列': 'ISR',
    '加拿大': 'CAN',
    '卡達': 'QAT',
    '史瓦濟蘭王國': 'SWZ',
    '甘比亞共和國': 'GMB',
    '白俄羅斯共和國': 'BLR',
    '立陶宛共和國': 'LTU',
    '伊朗伊斯蘭共和國': 'IRN',
    '冰島共和國': 'ISL',
    '列支敦斯登侯國': 'LIE',
    '匈牙利共和國': 'HUN',
    '印度尼西亞共和國': 'IDN',
    '印度共和國': 'IND',
    '西班牙王國': 'ESP',
    '克羅埃西亞共和國': 'HRV',
    '希臘共和國': 'GRC',
    '汶萊和平之國': 'BRN',
    '沙烏地阿拉伯王國': 'SAU',
    '貝里斯': 'BLZ',
    '邦交國吉里巴斯共和國': 'KIR',
    '邦交國帛琉共和國': 'PLW',
    '邦交國索羅門群島': 'SLB',
    '拉脫維亞共和國': 'LVA',
    '法國': 'FRA',
    '波蘭共和國': 'POL',
    '芬蘭共和國': 'FIN',
    '阿曼王國': 'OMN',
    '阿富汗伊斯蘭國': 'AFG',
    '俄羅斯聯邦': 'RUS',
    '南非共和國': 'ZAF',
    '柬埔寨王國': 'KHM',
    '科威特': 'KWT',
    '科索沃共和國': 'KOS',
    '突尼西亞共和國': 'TUN',
    '約旦哈什米王國': 'JOR',
    '美國': 'USA',
    '英國': 'GBR',
    '香港': 'HKG',
    '哥倫比亞共和國': 'COL',
    '哥斯大黎加共和國': 'CRI',
    '埃及阿拉伯共和國': 'EGY',
    '挪威王國': 'NOR',
    '格瑞那達': 'GRD',
    '泰王國(泰國)': 'THA',
    '紐西蘭': 'NZL',
    '馬來西亞': 'MYS',
    '馬爾他共和國': 'MLT',
    '捷克共和國': 'CZE',
    '荷蘭王國': 'NLD',
    '莫三比克共和國': 'MOZ',
    '斐濟群島共和國': 'FJI',
    '斯里蘭卡民主社會主義共和國': 'LKA',
    '斯洛伐克共和國': 'SVK',
    '斯洛維尼亞共和國': 'SVN',
    '智利': 'CHL',
    '朝鮮民主主義人民共和國(北韓)': 'PRK',
    '菲律賓共和國': 'PHL',
    '越南社會主義共和國': 'VNM',
    '塞席爾共和國': 'SYC',
    '奧地利共和國': 'AUT',
    '愛沙尼亞共和國': 'EST',
    '愛爾蘭共和國': 'IRL',
    '新加坡共和國': 'SGP',
    '瑞士聯邦': 'CHE',
    '瑞典王國': 'SWE',
    '義大利共和國': 'ITA',
    '聖多美普林西比民主共和國': 'STP',
    '葡萄牙共和國': 'PRT',
    '蒙古國': 'MNG',
    '墨西哥合眾國': 'MEX',
    '德意志聯邦共和國': 'DEU',
    '摩洛哥王國': 'MAR',
    '緬甸聯邦共和國': 'MMR',
    '澳大利亞': 'AUS',
    '澳門': 'MAC',
    '盧森堡大公國': 'LUX',
    '羅馬尼亞': 'ROU'
}

reader = csv.reader(open('exchange.csv', 'r', encoding='big5-hkscs'))
writer = csv.writer(open('out.csv','w', encoding='big5-hkscs'))
for row in reader:
    location = trans[row[7]] if row[7] in trans else row[7]
    school = row[9].upper()
    writer.writerow([row[0], row[1], row[2], row[3], row[4], row[5], row[6], location, row[8], school, row[10], row[11], row[12]])
